### ISSUE TITLE
Change how updates work and are shown in container overview table

### ISSUE THREAD

**Issue by nzxl101** [Notifiarr/dockwatch#19]
As discussed on Discord, the update status can sometimes be confusing that's why adding another status to the existing ones "Pulled" could be helpful indicating that a container image has been pulled and is ready to be updated since not everyone has auto-updates enabled: e.g. the overview will always show updated even though the container is not currently using the last pulled image hash (or I missed something?)
We could package [regclient](https://github.com/regclient/regclient) into the image and use it to check for updates instead of using "docker pull" which will always force pull the newest layers.

In addition to the Uptime of the container it would be good to show ~~when the container was last created with possibly~~ an image hash or version besides it. 

Let me know your thoughts 🙏

**Comment by austinwbest** [comment]
pulled time is the mouseover on the updates column
regctl is being implemented
not sure what hash you want to see where?

**Comment by austinwbest** [comment]
Ok, i added the image digest hash. It can be adjusted later if necessary
