### ISSUE TITLE
Settings do not appear to save?

### ISSUE THREAD

**Issue by CelticWebSolutions** [Notifiarr/dockwatch#24]
Setup via Portainer using 
`  dockwatch:
    container_name: dockwatch
    image: ghcr.io/notifiarr/dockwatch:main
    #ports:
      #- 9999:80/tcp
    environment:
      - PGID=999
      - TZ=Europe/London
    volumes:
      - ${DOCKER}/dockwatch:/config
      - /var/run/docker.sock:/var/run/docker.sock`
    
Container starts and runs fine, I can see all my containers. What it doesn't do is remember any of the settings I set and doesn't actually check any of the containers for updates.  I don't see anything in the log when I attempt to save and the screen says it's saved, but then when you check, the settings that were just set aren't still there? 

Possibly some kind of permissions issue but not sure where to check and what permissions they should be.

**Comment by bakerboy448** [comment]
Sounds like it doesn't have RW to /config

**Comment by CelticWebSolutions** [comment]
It should have, it created the files. I’ll go check again.

**Comment by austinwbest** [comment]
> Setup via Portainer using ` dockwatch: container_name: dockwatch image: ghcr.io/notifiarr/dockwatch:main #ports: #- 9999:80/tcp environment: - PGID=999 - TZ=Europe/London volumes: - ${DOCKER}/dockwatch:/config - /var/run/docker.sock:/var/run/docker.sock`
> 
> Container starts and runs fine, I can see all my containers. What it doesn't do is remember any of the settings I set and doesn't actually check any of the containers for updates. I don't see anything in the log when I attempt to save and the screen says it's saved, but then when you check, the settings that were just set aren't still there?
> 
> Possibly some kind of permissions issue but not sure where to check and what permissions they should be.

Can you hop on discord so we can sort it out?

**Comment by CelticWebSolutions** [comment]
Hi,

thanks, it appears that while it manager to create all the files, it had somehow created them as a different use and then wasn’t able to modify them, chown’d them back to the correct user and all seems well. Just looking at a few other little issues and it’ll be perfect.

I’ll join the discord :)

thanks again.
