### ISSUE TITLE
Various update issues

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/dockwatch#33]
so 3 issues
- [ ] secondary containers (e.g. radarr4k) not having pulls or updates done and incorrectly skipping: will add logging
- [ ] secondary containers (e.g. radarr4k) incorrectly being reported as up to date per manual pull and manual check for update.  yet the container needs to be creatd with the new image: tbd
- [ ] image labels need to be merged when recreating and override existing image labels, but keep container (i.e. non-image labels): to mesh and merge the image inspect

https://discord.com/channels/764440599066574859/1177302666309804214/1209996913722523678

**Comment by austinwbest** [comment]
I think all of this is sorted but i'll wait for you to get an update of multiple containers and verify
