### ISSUE TITLE
Feature request: Allow setting a custom timeout for container stopping

### ISSUE THREAD

**Issue by enchained** [Notifiarr/dockwatch#40]
Some containers, for example qbittorrent or databases, may need extra time to shutdown depending on usage. By default it's only 10 seconds before the kill, but in my case it may take up to 40 seconds to exit properly (and more in some extreme cases).

Premature kill of qbittorrent usually results in a very long resuming startup and extra HDD usage. There were hours of slow resuming in the logs until I tried stopping with docker compose down -t 120 instead, and now it is up and running in under 2 minutes.

**Comment by austinwbest** [comment]
This shouldnt be an issue, just need to figure out the best place to put the setting(s) since it isnt a global setting and will be on a container basis

**Comment by nzxl101** [comment]
Added in https://github.com/Notifiarr/dockwatch/commit/f208315c2ac9039bfe4c00005b4e60ef98fac6a7
