### ISSUE TITLE
Feature Request for Telegram Notification SUpport

### ISSUE THREAD

**Issue by iceman73** [Notifiarr/dockwatch#41]
I use Telegram for all my notifications of issues within my network, would love to move to this from Watchtower, but I need telegram notifications to a bot.

**Comment by austinwbest** [comment]
Unless someone does a PR for it, i wont get to it until i add telegram support to notifiarr so i have an understanding of their API, etc as i dont use it. No problem supporting other platforms, just not familiar with telegram yet

**Comment by austinwbest** [comment]
Added to `:develop`
