### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by Flyingfufu** [Notifiarr/dockwatch#49]
Hi,

Found this project few day ago, and I like it much ! Thanks for sharing this great tool.

I would like to make some suggestions that I would find very helpful :

1/ on the overview page, would be awesome to have the various category in "status", "health" or updates" as hyperlink, opening filtered related views.

2/ on the overview, change the network and ports windows in full width to have better visibility

![Capture d’écran 2024-12-08 152722 (1)](https://github.com/user-attachments/assets/bfa90534-2a61-425f-a4e4-69284d2faa70)
At least, more space between the text and the scroll bar would make it better to read.

3/ in the containers view, ability to filter, not only sort, the columns.

4/ in the containers view, keep the footer always visible
![image](https://github.com/user-attachments/assets/5ab3766f-e0f8-41d4-9cf9-22d267c93fac)

Also, should you be looking to make it multi language, I will be pleased to help for french translation.

**Comment by austinwbest** [comment]
1. I do not understand the request, opening what "filtered related views"
2. I dont mind to adjust the cards but i do not think they need to be fill width, there is very little information in them currently to use the entire page width. Would be 20% text and 80% dead space
3. There is a search box at the top right of the table to filter by table content already
4. Shouldnt be an issue to make the button row always visible
5. Im not sure if i'll convert all of the interface text to json strings but if there are others that are interested in helping then i wont mind to entertain the added work

**Comment by austinwbest** [comment]
Ive added some links & a detailed view to the overview page. Im not going to do anything with floating buttons on the containers page but i'll think on a different implementation for them. Was not liking how it overlayed the other rows & blocked them

![image](https://github.com/user-attachments/assets/508a34ea-ca29-412c-9a88-2c743e092134)

**Comment by austinwbest** [comment]
Moved the buttons to the top and float them when not mobile, we'll see how that works out

![image](https://github.com/user-attachments/assets/20840642-ebd2-4a12-9d01-3a02894501ff)

**Comment by Flyingfufu** [comment]
Like the version with the buttons on the top! Even better than keeping them on the bottom in my view.

**Comment by austinwbest** [comment]
Its pushed to main now so i'll close this up!
