### ISSUE TITLE
[FR] Option to set a minimum age (in days) before Auto updating

### ISSUE THREAD

**Issue by MattBlackOnly** [Notifiarr/dockwatch#50]
Allow images to mature before auto updating, which would hopefully prevent updating to troublesome images.

**Comment by austinwbest** [comment]
> Allow images to mature before auto updating, which would hopefully prevent updating to troublesome images.

Sorry for the delay, so you want to use the container added date as the threshold to compare to? If added < {date limit} then skip update and only notify even if auto update is enabled?

**Comment by austinwbest** [comment]
Something you want to tackle @nzxl101? I can if not, wont be hard to do. Add a `Min Age` column to the updates dialog for *n* days (default 0) & then just skip the update part in the cron and just fire a notification. Will need a db migration to add the field to the container table but no biggie

**Comment by nzxl101** [comment]
> Something you want to tackle @nzxl101? I can if not, wont be hard to do. Add a `Min Age` column to the updates dialog for _n_ days (default 0) & then just skip the update part in the cron and just fire a notification. Will need a db migration to add the field to the container table but no biggie

Added in https://github.com/Notifiarr/dockwatch/commit/524819e212c34aaba5a9340926374ec52bfbf3e6

**Comment by MattBlackOnly** [comment]
Thanks @nzxl101 and @austinwbest 

Quick follow up, what happens if there are two updates in quick succession? 

Say you have `Min Age` set to 10 days, and `image_update_a` is 9 days old and `image_update_b` is 5 days old, what happens the next day? 

Will `image_update_a` be skipped and nothing happens until `image_update_b` is 10 days old?

**Comment by nzxl101** [comment]
> Will image_update_a be skipped and nothing happens until image_update_b is 10 days old?  

We don't have a buffer for that as far as I know, so it's always gonna check for the latest digest hash (`sha256:xxxx`) that has been created, in this case it's `image_update_b`
Correct me if I'm wrong @austinwbest

**Comment by davidnewhall** [comment]
Do `image_update_a` and `image_update_b` refer to anything specific in the provided example? 

If the tracked tag (usually `latest`) is updated more often than every 9 days, it may not be possible to 'wait 10 days' because the tag is never that old. Check the software package for other tags that may be updated less frequently if this is an issue.

**Comment by MattBlackOnly** [comment]
> We don't have a buffer for that as far as I know, so it's always gonna check for the latest digest hash (`sha256:xxxx`) that has been created, in this case it's `image_update_b` Correct me if I'm wrong @austinwbest

That's perfect thanks
