### ISSUE TITLE
Mass Trigger Update: Skip containers that are set to "Ignore" or "Check for Updates"

### ISSUE THREAD

**Issue by nzxl101** [Notifiarr/dockwatch#9]
I've selected all containers to mass update without thinking about it too much and I've killed the main `dockwatch`  and `cloudflared` container 😅.
Would be nice if those containers that are set to `Ignore` or `Check for Updates` could get skipped.

**Comment by austinwbest** [comment]
Dockwatch should be hard coded to skip updating from the UI and from the cron 🤔
